application: c3po-bot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /groupme
  script: c3po.provider.groupme.receive.APP

- url: .*
  script: c3po.http_handler.APP
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- appengine_sdk.zip
- ^(.*/)?.*google_appengine/.*$
