application: c3po-bot
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: c3po.main.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- appengine_sdk.zip
- (google_appengine/.*)|
